pull_request_rules:
- name: merge pull requestst if CI passes
  conditions:
    - status-success=continuous-integration/travis-ci/pr
    - base=master
    - "#approved-reviews-by>=1"
  actions:
    delete_head_branch: {}
    merge:
      method: merge
