version: '3'
services:
  mongo:
    container_name: pritunldb
    hostname: pritunldb
    build:
      context: ./mongodb
    image: pritunldb
    networks:
      - private
    volumes:
      - /var/lib/mongo/data:/data/db    
  
  pritunl:
    environment:
      - MONGODB_SERVER=pritunldb
    container_name: pritunl
    hostname: pritunl
    privileged: true
    build:
      context: ./pritunl
    image: pritunl
    networks:
      - private
    ports:
      - "${PRIV_IP}:80:80"
      - "${PRIV_IP}:443:443"
      - "${PUB_IP}:1194:1194/udp"
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  private:
    driver: bridge
    internal: true
