version: '3'
services:
  mongo:
    container_name: pritunldb
    hostname: pritunldb
    build:
      context: ./mongodb
    image: pritunldb
    networks:
      - private
    volumes:
      - /var/lib/mongo/data:/data/db    
  
  pritunl:
    environment:
      - MONGODB_SERVER=pritunldb
    container_name: pritunl
    hostname: pritunl
    privileged: true
    build:
      context: ./pritunl
    image: pritunl
    networks:
      - private
      - proxy
    ports:
      - "1194:1194/udp"
    links:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

networks:
  proxy:
    external:
      name: proxy
  private:
    driver: bridge
    internal: true
